name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    # if: false # 自動テストなしにする場合、コメントを外す
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Node.js Setup
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0

      - name: Install Dependencies
        run: npm install

      - name: test run
        run: npm run test
